### ISSUE TITLE
Trace logging is always printed

### ISSUE THREAD

**Issue by XMol** [dCache/xrootd4j-cms-plugin#1]
Hlello dCache.org,

the logging ["matching rules for"](https://github.com/dCache/xrootd4j-cms-plugin/blob/472f9e4f073d03bd9ae7a97715ecd2806a23590a/src/main/scala/org/dcache/xrootd4j/CmsMappingHandler.scala#L42) shows up always in our dCache logfile, irrespective of the configured loglevel. Though the code says it should be of trace level, which is supposed to be filtered out for the default "warn" limit, right?

```
[f01-081-115] (local) admin > \s Xrootd-f01-080-109-e log ls
access:
  ROOT=OFF*
  org.dcache.access=INFO*
stdout:
  ROOT=WARN*
pinboard:
  ROOT=INFO*
events:
  ROOT=OFF*
  org.dcache.events=OFF*
```

The pinboard does not seem to be affected, i.e. "matching rules for" is not printed there.

The dCache version right now is 2.16.54 and for the plugin it is 1.3.7-1.

Can you possible tell me whether we can reduce the log level for the plugin specifically somehow?

Thanks,
Xavier.

**Comment by paulmillar** [comment]
Here's how it is supposed to work:

The TRACE log level is the lowest priority level available: all other log levels (DEBUG, INFO, WARN, ERROR) have a higher priority.

Thresholds work so that they let that priority level or higher; e.g., an INFO threshold allows messages with INFO, WARN or ERROR priority level, but excludes messages that have TRACE or DEBUG priority level.  There is also a special value (OFF) which disables all output.

Loggers form a hierarchy and thresholds apply to that point in the tree and deeper; e.g.,  `org.dcache.access=INFO` assertion affects the `org.dcache.access`, `org.dcache.access.ftp` and `org.dcache.access.http` loggers, but does not affect the `org.dcache.ftp` logger.  The keyword ROOT is a special case and selects all loggers.

The message you describe (`matching rules for...`) has TRACE level, which means the threshold needs to be set to TRACE before it is logged.

The domain log file is actually standard output, so is the `stdout` appender.  From the configuration (and by default) this accepts all WARN level messages.

This is all really just to say, from what you described, it shouldn't be logged.

**Comment by XMol** [comment]
Thanks for the confirmation, Paul!

Apart from that, to me it seems that the logging somehow bypasses the defined standards in dCache with regards to the format:

```
[root@f01-080-109-e ~]# head -3 /var/log/dcache/xrootd-f01-080-109-eDomain.log
matching rules for '/pnfs/gridka.de/cms/disk-only/store/user/pahrens/gc_storage/DoubleMuon_Run2017D-v1_RAW_freiburg_v1/Selection_data_2017_CMSSW9210_Run2017D/RAWskimmed/21/RAWskimmed_3320.root': None
matching rules for '/pnfs/gridka.de/cms/disk-only/store/user/pahrens/gc_storage/DoubleMuon_Run2017C-v3_RAW/Selection_data_2017_CMSSW923p2_Run2017C/RAWskimmed/51/RAWskimmed_450.root': None
matching rules for '/pnfs/gridka.de/cms/disk-only/store/user/pahrens/gc_storage/Run2017A_CMSSW923p2_Selection_v2/MuTau_MCDY_2017_CMSSW902_freiburg/Run2017B_CMSSW923p2_Selection/RAWskimmed/70/RAWskimmed_2869.root': None
```

The records are not printed with a timestamp, which should be added to each message by logback already, correct?

**Comment by paulmillar** [comment]
My guess is that this is some artefact of the code being Scala.

**Comment by XMol** [comment]
With our current versions - dcache v6.2.34, xrootd4j-cms-plugin 4.0.4 - this does no longer occur.
